FROM quay.io/jupyter/base-notebook:lab-4.4.7

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends libpq-dev git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN pip install --no-cache-dir psycopg2-binary sqlalchemy pandas scikit-learn
RUN pip install --no-cache-dir celine-utils

COPY ./config/jupyter/jupyterhub_config.py /home/jovyan/.jupyter/

COPY ./packages/jupyter_jwt_auth /opt/jupyter_jwt_auth
RUN pip install /opt/jupyter_jwt_auth

USER jovyan