version: "3"

tasks:
  start:
    desc: "Start containers"
    cmds:
      - docker compose up -d

  stop:
    desc: "Stop containers"
    cmds:
      - docker compose down

  restart:
    desc: "Stop containers"
    cmds:
      - task: stop
      - task: start

  reset:
    desc: "Stop and remove volumes"
    prompt: This will delete all the data and configuration. Continue ?
    cmds:
      - docker compose down -v

  logs:
    desc: "Show logs (pass service name with CLI_ARGS)"
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  ps:
    desc: "List containers"
    cmds:
      - docker compose ps

  dump-source:
    cmds:
      - python3 scripts/dump_source.py

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags
