version: "3"

tasks:
  setup:
    desc: "Setup services"
    cmds:
      - task: update-keycloak-client-secret
      - task: update-superset-secret
      - docker compose down superset && docker compose up -d superset

  ensure-env:
    cmds:
      - |
        if [ ! -f ./config/superset/.env ]; then
          echo "Creating .env from .env.example..."
          cp ./config/superset/.env.example ./config/superset/.env
        fi

  update-keycloak-client-secret:
    deps: [ensure-env]
    cmds:
      - |
        SECRET=$(cd ../../apps/celine-cli && task cli -- admin keycloak get-secret --client-id oauth2_proxy)
        PREFIX="KEYCLOAK_CLIENT_SECRET="
        sed -i "/^${PREFIX}/d" ./config/superset/.env
        # add carriage return
        echo "" >> ./config/superset/.env
        echo "${PREFIX}${SECRET}" >> ./config/superset/.env

  update-superset-secret:
    deps: [ensure-env]
    cmds:
      - |
        SECRET=$(openssl rand -base64 42)
        PREFIX="SUPERSET_SECRET_KEY="
        sed -i "/^${PREFIX}/d" ./config/superset/.env
        # add carriage return
        echo "" >> ./config/superset/.env
        echo "${PREFIX}${SECRET}" >> ./config/superset/.env

  start:
    desc: "Start containers"
    cmds:
      - docker compose up -d

  stop:
    desc: "Stop containers"
    cmds:
      - docker compose down

  restart:
    desc: "Stop containers"
    cmds:
      - task: stop
      - task: start

  reset:
    desc: "Stop and remove volumes"
    prompt: This will delete all the data and configuration. Continue ?
    cmds:
      - docker compose down -v

  logs:
    desc: "Show logs (pass service name with CLI_ARGS)"
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  ps:
    desc: "List containers"
    cmds:
      - docker compose ps

  dump-source:
    cmds:
      - python3 scripts/dump_source.py

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags
