version: "3"

tasks:
  governance:sync:
    desc: "Sync dataset governance"
    cmds:
      - |
        uv run celine-superset bootstrap
        uv run celine-superset governance sync \
          --path '../../../celine-pipelines/**/governance.yaml' \
          --path '../../../../../demo3/**/governance.yaml' \
          --owners '../../../dataset-api/owners.local.yaml' \
          --filter 'ds_dev_gold.*'
